package ru.danilakondr.les.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ru.danilakondr.les.expert.LittleExpertSystem;
import ru.danilakondr.les.knowbase.KnowledgeBase;
import ru.danilakondr.les.knowbase.KnowledgeBaseReader;

import javax.swing.*;
import javax.swing.filechooser.FileSystemView;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;

public class ExpertSystemForm {
    private JButton btnOpen;
    private JButton btnSaveProtocol;
    private JButton btnConf;
    private JTextPane tpComment;
    private JList<String> lstResults;
    private JList<String> lstProtocol;
    private JButton btnStartStop;
    private JTextField tfConfidenceValue;
    private JTextPane tpQuestion;
    private JList<String> lstQuestions;
    private JButton btnSendAnswer;
    private JPanel mainPanel;
    private JFrame frame;

    private final LittleExpertSystem les = new LittleExpertSystem();

    public ExpertSystemForm() {
        frame = new JFrame();


        btnSendAnswer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                float confidence = Float.parseFloat(tfConfidenceValue.getText());
                les.answer(confidence);
                update();
            }
        });

        lstResults.setModel(new AbstractListModel<String>() {
            @Override
            public int getSize() {
                return les.getCountOfHypotheses();
            }

            @Override
            public String getElementAt(int index) {
                return String.format("(%.5f) %s", les.getHypothesisValue(index), les.getHypothesisName(index));
            }
        });

        lstQuestions.setModel(new AbstractListModel<String>() {
            @Override
            public int getSize() {
                return les.getCountOfQuestions();
            }

            @Override
            public String getElementAt(int index) {
                return les.getQuestion(index);
            }
        });

        lstProtocol.setModel(new AbstractListModel<String>() {
            @Override
            public int getSize() {
                return les.getProtocol().getRecordCount();
            }

            @Override
            public String getElementAt(int index) {
                return les.getProtocol().getRecordString(index);
            }
        });
        btnOpen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser chooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
                chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

                int r = chooser.showOpenDialog(null);
                if (r == JFileChooser.APPROVE_OPTION) {
                    try {
                        loadKnowledgeBase(new KnowledgeBaseReader(chooser.getSelectedFile()).read());
                    } catch (IOException ex) {
                        throw new RuntimeException(ex);
                    }
                }
            }
        });
    }

    public void loadKnowledgeBase(KnowledgeBase kb) {
        les.loadKnowledgeBase(kb);
        update();
    }

    private void update() {
        lstQuestions.updateUI();
        lstResults.updateUI();
        lstProtocol.updateUI();
    }

    public void show() {
        frame.setContentPane(mainPanel);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JToolBar toolBar1 = new JToolBar();
        mainPanel.add(toolBar1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        btnOpen = new JButton();
        btnOpen.setText("Открыть БЗ");
        toolBar1.add(btnOpen);
        btnStartStop = new JButton();
        btnStartStop.setText("Запустить");
        toolBar1.add(btnStartStop);
        btnSaveProtocol = new JButton();
        btnSaveProtocol.setText("Выгрузить протокол");
        toolBar1.add(btnSaveProtocol);
        btnConf = new JButton();
        btnConf.setText("Настройки");
        toolBar1.add(btnConf);
        tpComment = new JTextPane();
        tpComment.setEditable(false);
        mainPanel.add(tpComment, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(150, 50), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lstProtocol = new JList();
        panel1.add(lstProtocol, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        lstResults = new JList();
        panel1.add(lstResults, new GridConstraints(0, 0, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Введите уровень уверенности");
        panel2.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfConfidenceValue = new JTextField();
        panel2.add(tfConfidenceValue, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnSendAnswer = new JButton();
        btnSendAnswer.setText("Отправить");
        panel2.add(btnSendAnswer, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tpQuestion = new JTextPane();
        tpQuestion.setEditable(false);
        panel1.add(tpQuestion, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel3.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        lstQuestions = new JList();
        scrollPane1.setViewportView(lstQuestions);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
